# CI for PuzzleBox.NeuralNets
# Restore > Build > Pack > Push

trigger:
- master

pool:
  vmImage: 'windows-2019'

variables:
  buildConfiguration: 'Release'

steps:

# Restore
- task: NuGetCommand@2
  displayName: "nuget restore"
  inputs:
    restoreSolution: '**/*.csproj'

# Build
- task: NuGetCommand@2
  displayName: "build"
  inputs:
    configuration: 'release'

# Pack
- task: DotNetCoreCLI@2
  inputs:
    command: 'pack'
    configuration: 'release'
    packagesToPack: PuzzleBox.NeuralNets/PuzzleBox.NeuralNets.csproj
    nobuild: true
