# CI for PuzzleBox.NeuralNets
# Build > Test > Pack > Push

trigger:
- master

pool:
  vmImage: 'windows-2019'

variables:
  buildConfiguration: 'Release'
  Major: '0'
  Minor: '1'
  Patch: '1'

steps:

# Build
- task: NuGetCommand@2
  displayName: "build"
  inputs:
    configuration: 'release'

# Test - TODO

# Pack
- task: DotNetCoreCLI@2
  inputs:
    command: 'pack'
    configuration: 'release'
    packagesToPack: PuzzleBox.NeuralNets/PuzzleBox.NeuralNets.csproj
    nobuild: true
    versioningScheme: byPrereleaseNumber
    majorVersion: '$(Major)'
    minorVersion: '$(Minor)'
    patchVersion: '$(Patch)'
    arguments: '--version-suffix alpha'

# Push
- task: DotNetCoreCLI@2
  inputs:
    command: 'push'
    configuration: 'release'
    packagesToPack: PuzzleBox.NeuralNets/PuzzleBox.NeuralNets.csproj
    nobuild: true
