# CI for PuzzleBox.NeuralNets
# Build & Test

trigger:
  branches:
    include:
    - master
  paths:
    exclude:
    - README.md
    - azure-pipelines.yml

pool:
  vmImage: 'windows-2019'

variables:
  buildConfiguration: 'Release'
  Major: '0'
  Minor: '1'
  Patch: '1'

steps:

# Build
- script: dotnet build -c $(buildConfiguration)
  displayName: 'Build'

# Test - TODO
